version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
    - 2.12.1
    - 3.0.0
    - 3.0.0
    - 3.0.0
    - 3.1.0
    - 3.3.0
    - 3.4.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
    - 4.4.0
  - dependency-name: gatsby-plugin-image
    versions:
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 4.1.0
    - 4.2.0
    - 4.3.0
    - 4.4.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.16.1
    - 3.1.0
    - 3.2.0
    - 4.0.0
    - 4.1.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.12.0
    - 0.12.2
    - 1.1.0
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.0
    - 2.11.1
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.0
    - 2.14.2
    - 2.14.3
    - 3.1.0
    - 3.1.1
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: gatsby
    versions:
    - 2.32.6
    - 2.32.8
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.1.0
    - 3.1.1
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: date-fns
    versions:
    - 2.20.1
    - 2.20.2
    - 2.20.3
  - dependency-name: "@types/react-helmet"
    versions:
    - 6.1.1
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.13
    - 7.13.14
  - dependency-name: typed.js
    versions:
    - 2.0.12
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.35
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.3
  - dependency-name: ts-jest
    versions:
    - 26.5.3
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: gatsby-image
    versions:
    - 2.11.0
    - 3.0.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
