sudo: required

env:
  global:
    - CC_TEST_REPORTER_ID=7672e20d57be9ceb1846716afe90826b89b13ff79a7172f1eb9927630d31e51e

services:
  - docker

before_install:
  - docker build -t marcelmichau/home-page -f Dockerfile.dev .

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - docker run -v $(pwd)/coverage:/app/coverage marcelmichau/home-page yarn test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
