sudo: required

services:
  - docker

before_install:
  - docker build -t marcelmichau/home-page -f Dockerfile.dev .

before_script:
  - docker run -e CC_TEST_REPORTER_ID -t marcelmichau/home-page ./cc-test-reporter before-build

script:
  - docker run -t marcelmichau/home-page yarn test
  - CONTAINER_ID=$(docker ps -alq)
  - docker cp $CONTAINER_ID:/app/coverage $(pwd)/coverage

after_script:
  - docker run -v $(pwd)/coverage:/app/coverage -e CC_TEST_REPORTER_ID -e CI -e TRAVIS -e TRAVIS_BUILD_NUMBER -e TRAVIS_BRANCH -e TRAVIS_COMMIT -t marcelmichau/home-page ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
