allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@5.20260908.0-alpha
  - wrangler@4.130.0
overrides:
  sharp@<0.35.4: ^0.35.4
