allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@5.20260908.0-alpha || 5.20260911.0-alpha || 5.20260915.0-alpha || 5.20260916.0-alpha
  - wrangler@4.130.0 || 4.131.1 || 4.132.0 || 4.133.0
overrides:
  sharp@<0.35.4: ^0.35.4
